# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "37fc1b80f7b202ca12cad41ff2260549"
application_url = "https://appfont--development.gadget.app/api/shopify/install-or-render"
embedded = true
name = "appfont"
handle = "appfont"

[webhooks]
api_version = "2024-10"

[auth]
redirect_urls = [
  "https://appfont--development.gadget.app/api/connections/auth/shopify/callback"
]

[build]
include_config_on_deploy = true
