# Learn more about working with Shopify TOML files with Gadget at https://docs.gadget.dev/guides/plugins/shopify/advanced-topics/shopify-app-toml

client_id = "cc3c31d5d686c9a698b83022c1053b50"
name = "fontify"
application_url = "https://appfont.gadget.app/api/shopify/install-or-render"
embedded = true

[auth]
redirect_urls = ["https://appfont.gadget.app/api/connections/auth/shopify/callback"]

[webhooks]
api_version = "2025-07"

[[webhooks.subscriptions]]
compliance_topics = [ "customers/data_request", "customers/redact" ,"shop/redact"]
uri = "https://appfont.gadget.app/api/webhooks/shopify"

[build]
automatically_update_urls_on_dev = false
dev_store_url = ""

[access_scopes]
scopes = "write_products,read_products,write_themes,read_themes"

[app_proxy]
url = "https://appfont.gadget.app/api/graphql"
subpath = "appfont-api"
prefix = "apps"